# Generated by Django 4.2.5 on 2023-09-20 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_id', models.CharField(max_length=200)),
                ('reportedBy', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_date', models.DateTimeField()),
                ('configuration', models.CharField(blank=True, max_length=200, null=True)),
                ('tail_number', models.CharField(blank=True, max_length=200, null=True)),
                ('mission_effect', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintananceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1', models.CharField(blank=True, max_length=200, null=True)),
                ('field_2', models.CharField(blank=True, max_length=200, null=True)),
                ('field_3', models.CharField(blank=True, max_length=200, null=True)),
                ('field_4', models.CharField(blank=True, max_length=200, null=True)),
                ('field_5', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='LocationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operating_mode', models.CharField(blank=True, max_length=200, null=True)),
                ('initial_severity', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_description', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
                ('maintenance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maintananceinfo')),
            ],
        ),
        migrations.CreateModel(
            name='IncidentAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_analysis', models.CharField(blank=True, max_length=200, null=True)),
                ('failure_detection', models.CharField(blank=True, max_length=200, null=True)),
                ('part_category', models.CharField(blank=True, max_length=200, null=True)),
                ('root_cause', models.CharField(blank=True, max_length=200, null=True)),
                ('analysis_result', models.TextField(blank=True, null=True)),
                ('analysis_recomendation', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='')),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_component', models.CharField(blank=True, max_length=200, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=200, null=True)),
                ('tsn', models.CharField(blank=True, max_length=200, null=True)),
                ('tso', models.CharField(blank=True, max_length=200, null=True)),
                ('oem', models.CharField(blank=True, max_length=200, null=True)),
                ('analysis_team', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
            ],
        ),
    ]
