# Generated by Django 4.2.5 on 2023-09-13 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='analysis',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incidentanalysis'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='detail_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incidentdetailinfo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='initial_info',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incidentinitialinfo'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='review',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incidentreview'),
        ),
        migrations.AlterField(
            model_name='incidentanalysis',
            name='failure_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentanalysis',
            name='root_cause',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentdetailinfo',
            name='relevant_category',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinitialinfo',
            name='configuration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinitialinfo',
            name='related_part',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentinitialinfo',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='analysis_team',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='bd_needed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='corrective_maintenance',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='customer_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='incident_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='operating_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='part_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='part_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='project_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='project_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='rca_needed',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreview',
            name='serial_number',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
