# Generated by Django 4.2.5 on 2023-09-21 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentinfo',
            name='current_state',
            field=models.CharField(default='NEW INCIDENT', max_length=200),
        ),
    ]
