# Generated by Django 4.2.5 on 2023-10-10 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdetails',
            old_name='incident_id',
            new_name='incident_ID',
        ),
        migrations.RenameField(
            model_name='incidentanalysis',
            old_name='incident_id',
            new_name='incident_ID',
        ),
        migrations.RenameField(
            model_name='incidentdetail',
            old_name='incident_id',
            new_name='incident_ID',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='incident_id',
            new_name='incident_ID',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='incident_id',
            new_name='incident_ID',
        ),
        migrations.RenameField(
            model_name='maintananceinfo',
            old_name='incident_id',
            new_name='incident_ID',
        ),
    ]
