# Generated by Django 4.2.5 on 2023-09-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_incidentinfo_current_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentanalysis',
            name='failure_mode',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
