# Generated by Django 4.2.5 on 2023-09-15 10:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_incident_analysis_alter_incident_detail_info_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='incidentdetailinfo',
            old_name='incident_description',
            new_name='fracas_incident_description',
        ),
        migrations.RenameField(
            model_name='incidentreview',
            old_name='incident_fracas_description',
            new_name='incident_description',
        ),
        migrations.RemoveField(
            model_name='incidentreview',
            name='incident_attachment',
        ),
        migrations.RemoveField(
            model_name='incidentreview',
            name='incident_type',
        ),
        migrations.AddField(
            model_name='incidentinitialinfo',
            name='incident_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
