# Generated by Django 4.2.5 on 2023-10-10 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_incident_id_equipmentdetails_incident_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipmentdetails',
            old_name='oem',
            new_name='meter_reading_tsn',
        ),
        migrations.RenameField(
            model_name='equipmentdetails',
            old_name='tsn',
            new_name='time_to_failure_tso',
        ),
        migrations.RenameField(
            model_name='equipmentdetails',
            old_name='tso',
            new_name='user_text10_oem',
        ),
        migrations.RenameField(
            model_name='incidentanalysis',
            old_name='attachment',
            new_name='attachments_analysis',
        ),
        migrations.RenameField(
            model_name='incidentanalysis',
            old_name='part_category',
            new_name='user_text11_team_analysis',
        ),
        migrations.RenameField(
            model_name='incidentanalysis',
            old_name='team_analysis',
            new_name='user_text16_part_category',
        ),
        migrations.RenameField(
            model_name='incidentdetail',
            old_name='attachment',
            new_name='attachments_incidents',
        ),
        migrations.RenameField(
            model_name='incidentdetail',
            old_name='incident_description',
            new_name='description_incident',
        ),
        migrations.RenameField(
            model_name='incidentdetail',
            old_name='initial_severity',
            new_name='user_text2_initial_severity',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='incident_date',
            new_name='occurrence_date',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='mission_effect',
            new_name='person_incident_entry',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='reportedBy',
            new_name='user_text13_tail_number',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='tail_number',
            new_name='user_text17_mission_effect',
        ),
        migrations.RenameField(
            model_name='incidentinfo',
            old_name='current_state',
            new_name='workflow_state',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='contact',
            new_name='user_text21_email',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='email',
            new_name='user_text22_phone',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='address',
            new_name='user_text24_address',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='location',
            new_name='user_text25_contact',
        ),
        migrations.RenameField(
            model_name='locationdetails',
            old_name='phone',
            new_name='user_text4_location',
        ),
        migrations.CreateModel(
            name='MaintenanceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_log_identifier', models.CharField(max_length=200)),
                ('override_system_tree_item_replaced_part', models.CharField(blank=True, max_length=200, null=True)),
                ('cost_item', models.FloatField(blank=True, null=True)),
                ('elapsed_maintenance_time', models.FloatField(blank=True, null=True)),
                ('cost_maintenance', models.FloatField(blank=True, null=True)),
                ('number_of_men', models.IntegerField(blank=True, null=True)),
                ('maintenance_start_date', models.DateTimeField()),
                ('total_maintenance_time', models.FloatField(blank=True, null=True)),
                ('user_value2_total_maintenance_time', models.FloatField(blank=True, null=True)),
                ('action_taken_maintenace', models.CharField(blank=True, max_length=200, null=True)),
                ('incident_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo')),
            ],
        ),
        migrations.AlterField(
            model_name='incidentdetail',
            name='maintenance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.maintenanceinfo'),
        ),
        migrations.DeleteModel(
            name='MaintananceInfo',
        ),
    ]
