# Generated by Django 4.2.5 on 2023-09-22 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_incidentanalysis_failure_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentdetails',
            name='incident_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.incidentinfo'),
        ),
    ]
