# Generated by Django 4.2.5 on 2023-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_incident_description_incidentdetailinfo_fracas_incident_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentanalysis',
            name='method',
            field=models.TextField(blank=True, null=True),
        ),
    ]
