# Generated by Django 4.2.5 on 2023-10-10 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_oem_equipmentdetails_meter_reading_tsn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentinfo',
            name='incident_ID',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
