# Generated by Django 4.2.5 on 2023-09-15 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_incidentinitialinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidentinitialinfo',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
