# Generated by Django 4.2.5 on 2023-11-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_locationdetails_user_text16_zip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatingTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.CharField(blank=True, max_length=200, null=True)),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('userText1', models.CharField(blank=True, max_length=200, null=True)),
                ('startDate', models.DateTimeField()),
                ('endDate', models.DateTimeField()),
                ('multiplicativeAdjustment', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
