# Generated by Django 4.2.5 on 2023-11-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_operatingtimes'),
    ]

    operations = [
        migrations.AddField(
            model_name='operatingtimes',
            name='operationalTime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
