# Generated by Django 4.2.5 on 2023-11-04 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_operatingtimes_operationaltime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='userText1',
            new_name='userText1_tail_number',
        ),
    ]
