# Generated by Django 4.2.5 on 2023-11-04 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_usertext1_operatingtimes_usertext1_tail_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='multiplicativeAdjustment',
            new_name='multiplicative_djustment',
        ),
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='operationalTime',
            new_name='operational_time',
        ),
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='startDate',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='operatingtimes',
            old_name='userText1_tail_number',
            new_name='user_text1_tail_number',
        ),
    ]
