# Generated by Django 4.2.5 on 2023-11-06 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_enddate_operatingtimes_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(blank=True, max_length=200, null=True)),
                ('project_id', models.CharField(max_length=200)),
                ('system_id', models.CharField(max_length=200)),
                ('configuration', models.CharField(max_length=200)),
                ('system_tree_item', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text22_failure_detection_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text23_failure_buque_situation', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text24_failure_effect_item', models.CharField(blank=True, max_length=200, null=True)),
                ('user_text25_failure_evidence', models.CharField(blank=True, max_length=200, null=True)),
                ('occurrence_date', models.DateTimeField()),
                ('occurrence_time', models.DateTimeField()),
                ('description_incident', models.TextField(blank=True, null=True)),
                ('user_text26_user_failure_detection', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
