# Generated by Django 4.2.5 on 2023-11-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_createincident_occurrence_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createincident',
            name='occurrence_time',
        ),
    ]
